[package]
name = "nlu-utils"
version = "0.2.0"
authors = ["Adrien Ball <adrien.ball@snips.ai>"]

[dependencies]
error-chain = { version = "0.10", default-features = false }
itertools = "0.6"
lazy_static = "0.2"
libc = "0.2"
regex = "0.2"
